const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  // 필요에 따라 수동 사이드바 항목 추가 가능
  // exampleSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
};

module.exports = sidebars;
